### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by SplendidAlakey** [Faboslav/friends-and-foes#108]
### Minecraft version information

1.19.4

### Mod loader information

Quilt

### Mod loader version information

0.18.10

### Mod version information

1.8.1

### Reproduction Steps

Simply install the mod and QSL, then run the game.

### Crash Report and latest.log

https://gist.github.com/SplendidAlakey/96a55dff15c2955b77a7fdefd12f75f7#file-crash-log

https://gist.github.com/SplendidAlakey/96a55dff15c2955b77a7fdefd12f75f7#file-latest-log

**Comment by TheGlitch76** [comment]
Since the Fabric jar works fine, but not the Quilt jar, I have a strong feeling the problem lies in Architectury's Quilt support. Something is going wrong in the remapping pipeline with QM, maybe?

(on a personal note, if you don't have any particular reason to maintain a separate Quilt codebase, you don't need to! having separate quilt and fabric versions of mods is a common source of pain for us when giving users support)

**Comment by Faboslav** [comment]
That is true, but based on the other linked issue even fabric version doesnt work on the quilt, so i am not sure what to do here :/.

**Comment by SplendidAlakey** [comment]
The Fabric version does work without any issues on Quilt Loader with QSL. Just tried it myself.

**Comment by Faboslav** [comment]
Hmm, then it's good news, i can't find the reply where someone mentioned that it doesnt work, but it's good to hear that it's working. Closing this issue for now with recommendation to use fabric version of the mod.
