### ISSUE TITLE
Server crash invalid dist DEDICATED_SERVER

### ISSUE THREAD

**Issue by Proxwian** [Faboslav/friends-and-foes#115]
### Minecraft version information

1.18.2

### Mod loader information

Forge

### Mod loader version information

40.2.4

### Mod version information

friendsandfoes-forge-mc1.18.2-1.4.7.jar

### Expected Behavior

Server will not crash causing client render problem

### Actual Behavior

Server crash with Copper Gollem involved

### Reproduction Steps

1. Currently does not know, it just crash for the first time

### Screenshots & files

[crash-2023-06-17_12.34.51-server.txt](https://github.com/Faboslav/friends-and-foes/files/11778971/crash-2023-06-17_12.34.51-server.txt)
[crash-2023-06-17_12.31.45-server.txt](https://github.com/Faboslav/friends-and-foes/files/11778972/crash-2023-06-17_12.31.45-server.txt)

**Comment by Faboslav** [comment]
This is caused by some other mod called `rhino`.

**Comment by Proxwian** [comment]
Rhino dev says there nothing rhino can do about it. Looks like friendsandfoes accessing client code from dedicated server somehow

**Comment by Proxwian** [comment]
![image](https://github.com/Faboslav/friends-and-foes/assets/31781674/62b90b0a-7165-48c5-8f3f-618f9e1b3a76)

**Comment by Faboslav** [comment]
After some digging I think I fixed this with the 1.19.x/1.20.x version of the mod. If i have some free time, i will try to do the same for 1.18.2, but as it is related to the two years old mc version, i am not sure if it is worth the time.

**Comment by Proxwian** [comment]
OMG, why r u so lazy

**Comment by Faboslav** [comment]
I am not happy, that there is this kind of bug left in the mod(it is fixed in newer versions), but I simply have more urgent stuff to do right now. 1.18 was released on November 30, 2021, that is 587 days. If you are unable to update mc version due to other mods not being updated, tell them that they are lazy and they should update.

Also it is worth to note, that right now i do keep support for 4 separate versions, 1.19, 1.19.3, 1.19.4, 1.20.x, so i am not exactly lazy.
