### ISSUE TITLE
[Suggestion] Pink variant of Mooblooms in cherry groves

### ISSUE THREAD

**Issue by MarioSMB** [Faboslav/friends-and-foes#133]
It would be really pretty to see a pink variant of the mooblooms in cherry groves!

**Comment by MarioSMB** [comment]
Seems to be a popular request around the Minecraft community, here's a video showing one design for them: https://www.youtube.com/watch?v=nlaDZJw_hKQ

**Comment by Faboslav** [comment]
Designs of all mooblooms are based on flowers, as you can see here https://www.curseforge.com/minecraft/mc-mods/friends-and-foes-flowery-mooblooms-fabric, there is already four pink-ish moobloom variants, such as Allium, Lilac, Peony and Pink Tulip.

Also since petals are not flowers, new moobloom variant will probably not be added. As of now mooblooms should spawn in cherry groove biome.

**Comment by MarioSMB** [comment]
I see - I wasn't aware of the secondary mod for moobloom variants, thanks!  

That said, the yellow mooblooms clash terribly with the surrounding pinkness of the biome, it may be better to leave them out of the biome when just using this mod!
